### PR TITLE
use apache-commons and apache-http plugins

### PR DESCRIPTION
**Pull request by don-vip**
These libraries are used by several plugins so I have created a single plugin to provide them to others, in order to avoid conflicts between different versions.

### CODE REVIEW

**Comment by kendzi** [comment]
Now To compile I need to download some strange project with stranger name "JOSM-apache-http". Where it is? Why to download it at all?

Why not to use maven and forget about dependencies?!

**Comment by kendzi** [comment]
Great, JOSM-apache-http depends on JOSM-apache-commons.

**Comment by kendzi** [comment]
And JOSM-apache-commons depends on JOSM-log4j.
But I would like to compile "my" project not all of them.

Really using maven does not hurt...

**Comment by kendzi** [comment]
Great, you put build-common.xml in root to make impossible for compile single plugin...

**Comment by kendzi** [comment]
Fixed version is released.

**Comment by don-vip** [comment]
Thanks for merging the PR. I know the build can be complicated for those who chose to host their plugin outside of the standard SVN repository. It is actually straightforward for standard ones, look at how simple is OSMRec's build.xml for example. Even areaselector is quite simple, although being on Github, because as it has been transferred to the JOSM organization, we can create an svn:external link to it, so it can benefit from the standard architecture.
That being said, a Maven repository containing standard plugins (i.e OSM SVN + JOSM Github) is a good idea, I'll see if we can create and maintain one easily. I'll let you know.

**Comment by kendzi** [comment]
Actually I'm using maven for my kendzi3d project, is working fine. I have jenkins job to build JOSM and put it inside my maven repository. It would be nice if you could create "official" artifact for at last JOSM itself (and some base plugins too). If you would like I can help with that.

**Comment by don-vip** [comment]
Yes, I can add JOSM also. I think I can handle it myself I already created one at work, stay tuned :)

**Comment by don-vip** [comment]
OK first, here is the repo for tested JOSM releases:
https://josm.openstreetmap.de/nexus/content/repositories/releases/org/openstreetmap/josm/josm/8800/josm-8800.pom

**Comment by don-vip** [comment]
Here is the SNAPSHOT, it will be updated each time we release a new "latest" version:
https://josm.openstreetmap.de/nexus/content/repositories/snapshots/org/openstreetmap/josm/josm/SNAPSHOT/

**Comment by don-vip** [comment]
OK it's done, you can use https://josm.openstreetmap.de/nexus/content/repositories/public/ as single repository for JOSM core and plugins. It is updated each time JOSM or a plugin is released.

**Pull request merged**
